platform :ios, '7.0'
pod 'ObjectiveSugar'
pod 'Masonry'
pod 'Reveal-iOS-SDK'
pod 'iCarousel', :git => 'https://github.com/bleeckerj/iCarousel'
pod 'FXLabel'
pod 'TTTAttributedLabel', :path => '~/Code/TTTAttributedLabel/'
pod 'FPBrandColors', '~> 0.1.3'
pod 'NSLogger'
